apiVersion: v1
kind: Service
metadata:
  name: raft-kv-service
  labels:
    app: raft-kv-store
spec:
  type: LoadBalancer
  selector:
    app: raft-kv-store
  ports:
    - name: grpc
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: http
      port: 9090
      targetPort: 9090
      protocol: TCP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
