apiVersion: v1
kind: Service
metadata:
  name: raft-kv-headless
  labels:
    app: raft-kv-store
spec:
  clusterIP: None
  selector:
    app: raft-kv-store
  ports:
    - name: grpc
      port: 8080
      targetPort: 8080
    - name: http
      port: 9090
      targetPort: 9090
    - name: metrics
      port: 9091
      targetPort: 9091
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: raft-kv-store
spec:
  serviceName: raft-kv-headless
  replicas: 3
  selector:
    matchLabels:
      app: raft-kv-store
  template:
    metadata:
      labels:
        app: raft-kv-store
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9091"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: raft-kv
        image: raft-kv-store:latest
        imagePullPolicy: IfNotPresent
        command:
          - /app/raft-kv-store
        args:
          - --id=$(POD_NAME)
          - --port=8080
          - --http-port=9090
          - --data-dir=/data
          - --peers=raft-kv-store-0,raft-kv-store-1,raft-kv-store-2
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        ports:
          - name: grpc
            containerPort: 8080
            protocol: TCP
          - name: http
            containerPort: 9090
            protocol: TCP
          - name: metrics
            containerPort: 9091
            protocol: TCP
        volumeMounts:
          - name: data
            mountPath: /data
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 9090
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 9090
          initialDelaySeconds: 10
          periodSeconds: 5
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: standard
      resources:
        requests:
          storage: 10Gi
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: raft-kv-pdb
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: raft-kv-store
